@startuml
skinparam classAttributeIconSize 0

note top of HumanAgents
  Table: HumanAgents
end note

class HumanAgents {
  +HumanAgentId: String
  +Name: String
  +Mbox: String
  +Roles: String
  +CountOfRles: Integer
  --
}

note top of Roles
  Table: Roles
end note

class Roles {
  +RoleId: String
  +Label: String
  +Comment: String
  +FilledBy: String
  +WorkflowSteps: String
  +CountOfWorkflowSteps: Integer
  +FilledByName: String
  +FilledByMBox: String
  --
}

note top of WorkflowSteps
  Table: WorkflowSteps
end note

class WorkflowSteps {
  +WorkflowStepId: String
  +Label: String
  +SequencePosition: Integer
  +RequiresHumanApproval: Boolean
  +IsStepOf: String
  +AssignedRole: String
  +IsStepOfTitle: String
  +IsStepOfDescription: String
  +IsStepOfIdentifier: String
  +AssignedRoleLabel: String
  +AssignedRoleComment: String
  +AssignedRoleFilledBy: String
  --
}

note top of Workflows
  Table: Workflows
end note

class Workflows {
  +WorkflowId: String
  +Title: String
  +Description: String
  +Created: String
  +Modified: String
  +Identifier: String
  +WorkflowSteps: String
  +CountOfWorkflowSteps: Integer
  --
}

@enduml