@startuml
skinparam classAttributeIconSize 0

note top of Customers
  Table: Customers
end note

class Customers {
  +CustomerId: String
  +Customer: String -- Identifier for the customers.
  +EmailAddress: String -- Thec ustomers email address
  +FirstName: String -- First Name of the customer - used to make the full name
  +LastName: String -- Last Name of the customer - used to make the full name
  --
  /FullName: String  {derived} -- Full name is computed from the first and last name of the customer
}

@enduml