       *> ERB Main Program (GENERATED - DO NOT EDIT)
       *> Reads tab-delimited input, computes fields, writes tab-delimited output
       *> Compile: cobc -free -x erb_main.cbl
       *> Run: ./erb_main < erb_input.tsv > erb_output.tsv
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ERBMAIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-EOF PIC 9 VALUE 0.
       01 WS-PTR PIC 9(4).
       01 WS-TAB PIC X VALUE X"09".
       01 WS-RECORD-COUNT PIC 9(6) VALUE 0.
       01 INPUT-LINE PIC X(5000).
       01 OUTPUT-LINE PIC X(5000).
       01 WS-TEMP-1 PIC X(500).
       01 WS-TEMP-2 PIC X(500).
       01 WS-TEMP-3 PIC X(500).
       01 WS-TEMP-4 PIC X(500).
       01 WS-TEMP-5 PIC X(500).
       01 WS-TEMP-6 PIC X(500).
       01 WS-TEMP-7 PIC X(500).
       01 WS-TEMP-8 PIC X(500).
       01 WS-TEMP-9 PIC X(500).
       01 WS-TEMP-10 PIC X(500).
       01 WS-FIND-NEEDLE   PIC X(500).
       01 WS-FIND-HAYSTACK PIC X(500).
       01 WS-FIND-RESULT   PIC X(5).
       01 WS-FIND-I       PIC 9(6).
       01 WS-FIND-LEN     PIC 9(6).
       01 WS-FIND-NLEN    PIC 9(6).
       01 WS-SUBST-INPUT  PIC X(500).
       01 WS-SUBST-OLD    PIC X(100).
       01 WS-SUBST-NEW    PIC X(100).
       01 WS-SUBST-OUTPUT PIC X(500).
       01 WS-SUBST-I      PIC 9(6).
       01 WS-SUBST-OUT-I  PIC 9(6).
       01 WS-SUBST-INLEN  PIC 9(6).
       01 WS-SUBST-OLDLEN PIC 9(6).
       01 WS-SUBST-NEWLEN PIC 9(6).
       01 WS-REC.
          02 WS-REC-SHAPE-ID PIC X(500).
          02 WS-REC-NAME PIC X(500).
          02 WS-REC-SIDES PIC X(500).
          02 WS-REC-HOW-MANY-SIDES PIC 9(10).
          02 WS-REC-SUM-OF-INTERNAL-ANGLES PIC X(500).
          02 WS-REC-MAX-ANGLE PIC X(500).
          02 WS-REC-HYPOTENUSE-LENGTH-SQUARED PIC X(500).
          02 WS-REC-NON-HYPOTENUSE-SIDES-SQUARED PIC X(500).
          02 WS-REC-IS-RECTANGLE PIC X(5).
          02 WS-REC-IS-TRIANGLE PIC X(5).
          02 WS-REC-IS-RIGHT-TRIANGLE PIC X(5).
          02 WS-REC-PYTHAGOREAN-THEOREM-HOLDS PIC X(5).
       PROCEDURE DIVISION.
       MAIN-PARA.
           PERFORM READ-AND-PROCESS UNTIL WS-EOF = 1
           STOP RUN.

       READ-AND-PROCESS.
           MOVE SPACES TO INPUT-LINE
           ACCEPT INPUT-LINE
           IF INPUT-LINE = SPACES
               MOVE 1 TO WS-EOF
           ELSE
               PERFORM PROCESS-RECORD
           END-IF.

       PROCESS-RECORD.
           PERFORM PARSE-INPUT
           PERFORM COMPUTE-ALL-FIELDS
           PERFORM WRITE-OUTPUT
           ADD 1 TO WS-RECORD-COUNT.

       PARSE-INPUT.
           MOVE 1 TO WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-SHAPE-ID
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-NAME
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-SIDES
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-HOW-MANY-SIDES
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-SUM-OF-INTERNAL-ANGLES
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-MAX-ANGLE
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-HYPOTENUSE-LENGTH-SQUARED
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB OR SPACES
               INTO WS-REC-NON-HYPOTENUSE-SIDES-SQUARED
               WITH POINTER WS-PTR
           .

       *> Level 1
       CALC-IS-RECTANGLE.
           IF (((WS-REC-HOW-MANY-SIDES = 4)))
               MOVE "true" TO WS-REC-IS-RECTANGLE
           ELSE
               MOVE "false" TO WS-REC-IS-RECTANGLE
           END-IF
       .

       CALC-IS-TRIANGLE.
           IF (((WS-REC-SUM-OF-INTERNAL-ANGLES = 180)) AND ((WS-REC-HOW-MANY-SIDES = 3)))
               MOVE "true" TO WS-REC-IS-TRIANGLE
           ELSE
               MOVE "false" TO WS-REC-IS-TRIANGLE
           END-IF
       .

       *> Level 2
       CALC-IS-RIGHT-TRIANGLE.
           IF ((WS-REC-IS-TRIANGLE = "true") AND ((WS-REC-MAX-ANGLE = 90)))
               MOVE "true" TO WS-REC-IS-RIGHT-TRIANGLE
           ELSE
               MOVE "false" TO WS-REC-IS-RIGHT-TRIANGLE
           END-IF
       .

       *> Level 3
       CALC-PYTHAGOREAN-THEOREM-HOLDS.
           IF ((WS-REC-IS-RIGHT-TRIANGLE = "true") AND ((WS-REC-HYPOTENUSE-LENGTH-SQUARED = WS-REC-NON-HYPOTENUSE-SIDES-SQUARED)))
               MOVE "true" TO WS-REC-PYTHAGOREAN-THEOREM-HOLDS
           ELSE
               MOVE "false" TO WS-REC-PYTHAGOREAN-THEOREM-HOLDS
           END-IF
       .

       COMPUTE-ALL-FIELDS.
           PERFORM CALC-IS-RECTANGLE
           PERFORM CALC-IS-TRIANGLE
           PERFORM CALC-IS-RIGHT-TRIANGLE
           PERFORM CALC-PYTHAGOREAN-THEOREM-HOLDS
       .

       WRITE-OUTPUT.
           MOVE SPACES TO OUTPUT-LINE
           STRING
               FUNCTION TRIM(WS-REC-SHAPE-ID TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-NAME TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-SIDES TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-HOW-MANY-SIDES TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-SUM-OF-INTERNAL-ANGLES TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-MAX-ANGLE TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-HYPOTENUSE-LENGTH-SQUARED TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-NON-HYPOTENUSE-SIDES-SQUARED TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-IS-RECTANGLE TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-IS-TRIANGLE TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-IS-RIGHT-TRIANGLE TRAILING) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-PYTHAGOREAN-THEOREM-HOLDS TRAILING) DELIMITED SIZE
               INTO OUTPUT-LINE
           DISPLAY FUNCTION TRIM(OUTPUT-LINE TRAILING)
           .

       FIND-CONTAINS.
           MOVE "false" TO WS-FIND-RESULT
           MOVE 1 TO WS-FIND-I
           COMPUTE WS-FIND-LEN = FUNCTION LENGTH(WS-FIND-HAYSTACK)
           COMPUTE WS-FIND-NLEN = FUNCTION LENGTH(WS-FIND-NEEDLE)
           IF WS-FIND-NLEN = 0
               MOVE "true" TO WS-FIND-RESULT
           END-IF
           PERFORM UNTIL WS-FIND-I > WS-FIND-LEN - WS-FIND-NLEN + 1
               OR WS-FIND-RESULT = "true"
               IF WS-FIND-HAYSTACK(WS-FIND-I:WS-FIND-NLEN) = WS-FIND-NEEDLE
                   MOVE "true" TO WS-FIND-RESULT
               END-IF
               ADD 1 TO WS-FIND-I
           END-PERFORM
           .

       SUBSTITUTE-ALL.
           MOVE SPACES TO WS-SUBST-OUTPUT
           MOVE 1 TO WS-SUBST-I
           MOVE 1 TO WS-SUBST-OUT-I
           COMPUTE WS-SUBST-INLEN = FUNCTION LENGTH(
               FUNCTION TRIM(WS-SUBST-INPUT))
*>         For single-char replacement, hardcode length to 1
           MOVE 1 TO WS-SUBST-OLDLEN
           MOVE 1 TO WS-SUBST-NEWLEN
           PERFORM UNTIL WS-SUBST-I > WS-SUBST-INLEN
               IF WS-SUBST-INPUT(WS-SUBST-I:1) = WS-SUBST-OLD(1:1)
                   MOVE WS-SUBST-NEW(1:1)
                       TO WS-SUBST-OUTPUT(WS-SUBST-OUT-I:1)
                   ADD 1 TO WS-SUBST-OUT-I
                   ADD 1 TO WS-SUBST-I
               ELSE
                   MOVE WS-SUBST-INPUT(WS-SUBST-I:1)
                       TO WS-SUBST-OUTPUT(WS-SUBST-OUT-I:1)
                   ADD 1 TO WS-SUBST-I
                   ADD 1 TO WS-SUBST-OUT-I
               END-IF
           END-PERFORM
       .
