       *> ERB Main Program (GENERATED - DO NOT EDIT)
       *> Reads tab-delimited input, computes fields, writes tab-delimited output
       *> Compile: cobc -free -x erb_main.cbl
       *> Run: ./erb_main < erb_input.tsv > erb_output.tsv
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ERBMAIN.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-EOF PIC 9 VALUE 0.
       01 WS-PTR PIC 9(4).
       01 WS-TAB PIC X VALUE X"09".
       01 WS-RECORD-COUNT PIC 9(6) VALUE 0.
       01 INPUT-LINE PIC X(5000).
       01 OUTPUT-LINE PIC X(5000).
       01 WS-TEMP-1 PIC X(500).
       01 WS-TEMP-2 PIC X(500).
       01 WS-TEMP-3 PIC X(500).
       01 WS-TEMP-4 PIC X(500).
       01 WS-TEMP-5 PIC X(500).
       01 WS-TEMP-6 PIC X(500).
       01 WS-TEMP-7 PIC X(500).
       01 WS-TEMP-8 PIC X(500).
       01 WS-TEMP-9 PIC X(500).
       01 WS-TEMP-10 PIC X(500).
       01 WS-FIND-NEEDLE   PIC X(500).
       01 WS-FIND-HAYSTACK PIC X(500).
       01 WS-FIND-RESULT   PIC X(5).
       01 WS-FIND-I       PIC 9(6).
       01 WS-FIND-LEN     PIC 9(6).
       01 WS-FIND-NLEN    PIC 9(6).
       01 WS-SUBST-INPUT  PIC X(500).
       01 WS-SUBST-OLD    PIC X(100).
       01 WS-SUBST-NEW    PIC X(100).
       01 WS-SUBST-OUTPUT PIC X(500).
       01 WS-SUBST-I      PIC 9(6).
       01 WS-SUBST-OUT-I  PIC 9(6).
       01 WS-SUBST-INLEN  PIC 9(6).
       01 WS-SUBST-OLDLEN PIC 9(6).
       01 WS-SUBST-NEWLEN PIC 9(6).
       01 WS-REC.
          02 WS-REC-WORKFLOW-ID PIC X(500).
          02 WS-REC-DISPLAY-NAME PIC X(500).
          02 WS-REC-TITLE PIC X(500).
          02 WS-REC-COLOR PIC X(500).
          02 WS-REC-DESCRIPTION PIC X(500).
          02 WS-REC-IDENTIFIER PIC X(500).
          02 WS-REC-MODIFIED PIC X(500).
          02 WS-REC-WORKFLOW-STEPS PIC X(500).
          02 WS-REC-COUNT-OF-NON-PROPOSED-STEPS PIC 9(10).
          02 WS-REC-NAME PIC X(500).
          02 WS-REC-HAS-MORE-THAN1-STEP PIC X(5).
       PROCEDURE DIVISION.
       MAIN-PARA.
           PERFORM READ-AND-PROCESS UNTIL WS-EOF = 1
           STOP RUN.

       READ-AND-PROCESS.
           MOVE SPACES TO INPUT-LINE
           ACCEPT INPUT-LINE
           IF INPUT-LINE = SPACES
               MOVE 1 TO WS-EOF
           ELSE
               PERFORM PROCESS-RECORD
           END-IF.

       PROCESS-RECORD.
           PERFORM PARSE-INPUT
           PERFORM COMPUTE-ALL-FIELDS
           PERFORM WRITE-OUTPUT
           ADD 1 TO WS-RECORD-COUNT.

       PARSE-INPUT.
           MOVE 1 TO WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-WORKFLOW-ID
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-DISPLAY-NAME
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-TITLE
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-COLOR
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-DESCRIPTION
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-IDENTIFIER
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-MODIFIED
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB
               INTO WS-REC-WORKFLOW-STEPS
               WITH POINTER WS-PTR
           UNSTRING INPUT-LINE DELIMITED BY WS-TAB OR SPACES
               INTO WS-REC-COUNT-OF-NON-PROPOSED-STEPS
               WITH POINTER WS-PTR
           .

       *> Level 1
       CALC-NAME.
           MOVE FUNCTION LOWER-CASE(WS-REC-DISPLAY-NAME) TO WS-TEMP-1
           MOVE WS-TEMP-1 TO WS-SUBST-INPUT
           MOVE " " TO WS-SUBST-OLD
           MOVE "-" TO WS-SUBST-NEW
           PERFORM SUBSTITUTE-ALL
           MOVE WS-SUBST-OUTPUT TO WS-REC-NAME
       .

       CALC-HAS-MORE-THAN1-STEP.
           IF (WS-REC-COUNT-OF-NON-PROPOSED-STEPS > 1)
               MOVE "True" TO WS-REC-HAS-MORE-THAN1-STEP
           ELSE
               MOVE "False" TO WS-REC-HAS-MORE-THAN1-STEP
           END-IF
       .

       COMPUTE-ALL-FIELDS.
           PERFORM CALC-NAME
           PERFORM CALC-HAS-MORE-THAN1-STEP
       .

       WRITE-OUTPUT.
           MOVE SPACES TO OUTPUT-LINE
           STRING
               FUNCTION TRIM(WS-REC-WORKFLOW-ID) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-DISPLAY-NAME) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-TITLE) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-COLOR) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-DESCRIPTION) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-IDENTIFIER) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-MODIFIED) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-WORKFLOW-STEPS) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-COUNT-OF-NON-PROPOSED-STEPS) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-NAME) DELIMITED SIZE
               WS-TAB DELIMITED SIZE
               FUNCTION TRIM(WS-REC-HAS-MORE-THAN1-STEP) DELIMITED SIZE
               INTO OUTPUT-LINE
           DISPLAY FUNCTION TRIM(OUTPUT-LINE)
           .

       FIND-CONTAINS.
           MOVE "false" TO WS-FIND-RESULT
           MOVE 1 TO WS-FIND-I
           COMPUTE WS-FIND-LEN = FUNCTION LENGTH(WS-FIND-HAYSTACK)
           COMPUTE WS-FIND-NLEN = FUNCTION LENGTH(WS-FIND-NEEDLE)
           IF WS-FIND-NLEN = 0
               MOVE "true" TO WS-FIND-RESULT
           END-IF
           PERFORM UNTIL WS-FIND-I > WS-FIND-LEN - WS-FIND-NLEN + 1
               OR WS-FIND-RESULT = "true"
               IF WS-FIND-HAYSTACK(WS-FIND-I:WS-FIND-NLEN) = WS-FIND-NEEDLE
                   MOVE "true" TO WS-FIND-RESULT
               END-IF
               ADD 1 TO WS-FIND-I
           END-PERFORM
           .

       SUBSTITUTE-ALL.
           MOVE SPACES TO WS-SUBST-OUTPUT
           MOVE 1 TO WS-SUBST-I
           MOVE 1 TO WS-SUBST-OUT-I
           COMPUTE WS-SUBST-INLEN = FUNCTION LENGTH(
               FUNCTION TRIM(WS-SUBST-INPUT))
*>         For single-char replacement, hardcode length to 1
           MOVE 1 TO WS-SUBST-OLDLEN
           MOVE 1 TO WS-SUBST-NEWLEN
           PERFORM UNTIL WS-SUBST-I > WS-SUBST-INLEN
               IF WS-SUBST-INPUT(WS-SUBST-I:1) = WS-SUBST-OLD(1:1)
                   MOVE WS-SUBST-NEW(1:1)
                       TO WS-SUBST-OUTPUT(WS-SUBST-OUT-I:1)
                   ADD 1 TO WS-SUBST-OUT-I
                   ADD 1 TO WS-SUBST-I
               ELSE
                   MOVE WS-SUBST-INPUT(WS-SUBST-I:1)
                       TO WS-SUBST-OUTPUT(WS-SUBST-OUT-I:1)
                   ADD 1 TO WS-SUBST-I
                   ADD 1 TO WS-SUBST-OUT-I
               END-IF
           END-PERFORM
       .
