-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 5
-- Total Raw Fields: 16
-- ============================================================================

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_human_agents_count_of_rles(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_roles_count_of_workflow_steps(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_roles_filled_by_m_box(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_roles_filled_by_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_assigned_role_comment(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_assigned_role_filled_by(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_assigned_role_label(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_is_step_of_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_is_step_of_identifier(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflow_steps_is_step_of_title(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_workflows_count_of_workflow_steps(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_human_agents_mbox(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_human_agents_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_roles_comment(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_roles_label(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflow_steps_label(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflow_steps_requires_human_approval(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflow_steps_sequence_position(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflows_created(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflows_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflows_identifier(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflows_modified(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_workflows_title(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_human_agents CASCADE;
DROP VIEW IF EXISTS vw_name CASCADE;
DROP VIEW IF EXISTS vw_roles CASCADE;
DROP VIEW IF EXISTS vw_workflow_steps CASCADE;
DROP VIEW IF EXISTS vw_workflows CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS human_agents CASCADE;
DROP TABLE IF EXISTS name CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS workflow_steps CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

CREATE TABLE name (
);

CREATE TABLE workflows (
  workflow_id                         TEXT                 PRIMARY KEY,
  title                               TEXT                ,
  description                         TEXT                ,
  created                             TIMESTAMPTZ         ,
  modified                            TIMESTAMPTZ         ,
  identifier                          TEXT                
);
COMMENT ON TABLE workflows IS 'Table: Workflows';

CREATE TABLE workflow_steps (
  workflow_step_id                    TEXT                 PRIMARY KEY,
  label                               TEXT                ,
  sequence_position                   INTEGER             ,
  requires_human_approval             BOOLEAN             ,
  is_step_of                          TEXT                ,
  assigned_role                       TEXT                
);
COMMENT ON TABLE workflow_steps IS 'Table: WorkflowSteps';

CREATE TABLE roles (
  role_id                             TEXT                 PRIMARY KEY,
  label                               TEXT                ,
  comment                             TEXT                ,
  filled_by                           TEXT                ,
  workflow_steps                      TEXT                
);
COMMENT ON TABLE roles IS 'Table: Roles';

CREATE TABLE human_agents (
  human_agent_id                      TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  mbox                                TEXT                ,
  roles                               TEXT                
);
COMMENT ON TABLE human_agents IS 'Table: HumanAgents';

