-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

CREATE OR REPLACE FUNCTION get_workflow_steps_display_name(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflow_steps_sequence_position(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT sequence_position FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflow_steps_requires_human_approval(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (SELECT requires_human_approval FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflows_name(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM workflows WHERE workflow_id = p_workflow_id)), ' ', '-'))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflows_count_of_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflows_has_more_than1_step(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (calc_workflows_count_of_steps(p_workflow_id) > 1)::boolean;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflow_steps_assigned_role_department(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT owned_by::text FROM roles WHERE role_id = (SELECT assigned_role FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflow_steps_approval_gate_escalation_threshold_hours(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT escalation_threshold_hours::integer FROM approvals WHERE approval_id = (SELECT approval_gate FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflows_display_name(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM workflows WHERE workflow_id = p_workflow_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflows_title(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title FROM workflows WHERE workflow_id = p_workflow_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflows_description(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description FROM workflows WHERE workflow_id = p_workflow_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflows_identifier(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT identifier FROM workflows WHERE workflow_id = p_workflow_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflows_modified(p_workflow_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT modified FROM workflows WHERE workflow_id = p_workflow_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_roles_display_name(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM roles WHERE role_id = p_role_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_roles_label(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT label FROM roles WHERE role_id = p_role_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_roles_comment(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT comment FROM roles WHERE role_id = p_role_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_approvals_display_name(p_approval_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM approvals WHERE approval_id = p_approval_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_approvals_escalation_threshold_hours(p_approval_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT escalation_threshold_hours FROM approvals WHERE approval_id = p_approval_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_precedes_steps_name(p_precedes_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM precedes_steps WHERE precedes_step_id = p_precedes_step_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_precedes_steps_step_number(p_precedes_step_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT step_number FROM precedes_steps WHERE precedes_step_id = p_precedes_step_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_step_transitions_name(p_step_transition_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM step_transitions WHERE step_transition_id = p_step_transition_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflow_artifacts_artifact_name(p_workflow_artifact_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT artifact_name FROM workflow_artifacts WHERE workflow_artifact_id = p_workflow_artifact_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflow_artifacts_artifact_description(p_workflow_artifact_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT artifact_description FROM workflow_artifacts WHERE workflow_artifact_id = p_workflow_artifact_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_workflow_artifacts_artifact_file(p_workflow_artifact_id TEXT)
RETURNS BYTEA AS $$
BEGIN
  RETURN (SELECT artifact_file FROM workflow_artifacts WHERE workflow_artifact_id = p_workflow_artifact_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflow_steps_name(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id)), ' ', '-'))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflow_steps_execution_actor_type(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CASE WHEN calc_workflow_steps_assigned_role_department(p_workflow_step_id) = 'HumanAgent' THEN 'HumanAgent' ELSE CASE WHEN calc_workflow_steps_assigned_role_department(p_workflow_step_id) = 'AIAgent' THEN 'AIAgent' ELSE CASE WHEN calc_workflow_steps_assigned_role_department(p_workflow_step_id) = 'AutomatedPipeline' THEN 'AutomatedPipeline' ELSE NULL END END END)::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_approvals_workflow_from_workflow_steps(p_approval_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT workflow::text FROM workflow_steps WHERE workflow_step_id = (SELECT workflow_steps FROM approvals WHERE approval_id = p_approval_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_approvals_assigned_role_from_workflow_steps(p_approval_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT assigned_role::text FROM workflow_steps WHERE workflow_step_id = (SELECT workflow_steps FROM approvals WHERE approval_id = p_approval_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_approvals_sequence_position_from_workflow_steps(p_approval_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT sequence_position::integer FROM workflow_steps WHERE workflow_step_id = (SELECT workflow_steps FROM approvals WHERE approval_id = p_approval_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_approvals_requires_human_approval_from_workflow_steps(p_approval_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (SELECT requires_human_approval::boolean FROM workflow_steps WHERE workflow_step_id = (SELECT workflow_steps FROM approvals WHERE approval_id = p_approval_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_approvals_name(p_approval_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM approvals WHERE approval_id = p_approval_id)), ' ', '-'))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_precedes_steps_display_name(p_precedes_step_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CONCAT('Step-', (SELECT step_number FROM precedes_steps WHERE precedes_step_id = p_precedes_step_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_roles_all_linked_workflow_steps(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(DISTINCT name::text, ', ') FROM workflow_steps WHERE assigned_role = p_role_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_roles_distinct_workflows_for_linked_steps(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(DISTINCT workflow::text, ', ') FROM workflow_steps WHERE assigned_role = p_role_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_human_agents_name(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM human_agents WHERE human_agent_id = p_human_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_human_agents_display_name(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM human_agents WHERE human_agent_id = p_human_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_human_agents_mbox(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT mbox FROM human_agents WHERE human_agent_id = p_human_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ai_agents_name(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ai_agents_title(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ai_agents_display_name(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ai_agents_model_version(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT model_version FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_automated_pipelines_name(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_automated_pipelines_description(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_automated_pipelines_display_name(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_departments_title(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title FROM departments WHERE department_id = p_department_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_departments_display_name(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT display_name FROM departments WHERE department_id = p_department_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_roles_name(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (LOWER((SELECT NULLIF(display_name, '') FROM roles WHERE role_id = p_role_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_departments_all_owned_roles(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(DISTINCT display_name::text, ', ') FROM roles WHERE owned_by = p_department_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_departments_all_related_workflow_steps(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(DISTINCT all_linked_workflow_steps::text, ', ') FROM roles WHERE owned_by = p_department_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_departments_all_distinct_workflows_for_owned_roles(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(DISTINCT distinct_workflows_for_linked_steps::text, ', ') FROM roles WHERE owned_by = p_department_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_departments_name(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM departments WHERE department_id = p_department_id)), ' ', '-'))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_human_agents_all_linked_roles(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_roles_name((SELECT roles FROM human_agents WHERE human_agent_id = p_human_agent_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_human_agents_all_related_workflow_steps(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_roles_all_linked_workflow_steps((SELECT roles FROM human_agents WHERE human_agent_id = p_human_agent_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_human_agents_all_distinct_workflows_for_linked_roles(p_human_agent_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_roles_distinct_workflows_for_linked_steps((SELECT roles FROM human_agents WHERE human_agent_id = p_human_agent_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_step_transitions_workflow_from_from_step(p_step_transition_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT workflow::text FROM workflow_steps WHERE workflow_step_id = (SELECT from_step FROM step_transitions WHERE step_transition_id = p_step_transition_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_workflow_from_produced_by_step(p_workflow_artifact_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT workflow::text FROM workflow_steps WHERE workflow_step_id = (SELECT produced_by_step FROM workflow_artifacts WHERE workflow_artifact_id = p_workflow_artifact_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

CREATE OR REPLACE FUNCTION calc_workflows_workflow_steps(p_workflow_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(workflow_step_id::TEXT, ', ' ORDER BY workflow_step_id)
    FROM workflow_steps
    WHERE workflow = p_workflow_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION calc_roles_workflow_steps(p_role_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(workflow_step_id::TEXT, ', ' ORDER BY workflow_step_id)
    FROM workflow_steps
    WHERE assigned_role = p_role_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION calc_departments_roles(p_department_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(role_id::TEXT, ', ' ORDER BY role_id)
    FROM roles
    WHERE owned_by = p_department_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

