-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 14
-- ============================================================================

CREATE OR REPLACE VIEW vw_workflows WITH (security_invoker = ON) AS
SELECT
  t.workflow_id,
  calc_workflows_name(t.workflow_id) AS name,
  t.display_name,
  t.title,
  t.description,
  t.identifier,
  t.modified,
  calc_workflows_workflow_steps(t.workflow_id) AS workflow_steps,
  calc_workflows_count_of_steps(t.workflow_id) AS count_of_steps,
  calc_workflows_has_more_than1_step(t.workflow_id) AS has_more_than1_step
FROM workflows t;

CREATE OR REPLACE VIEW vw_workflow_steps WITH (security_invoker = ON) AS
SELECT
  t.workflow_step_id,
  calc_workflow_steps_name(t.workflow_step_id) AS name,
  t.display_name,
  t.workflow,
  t.sequence_position,
  t.assigned_role,
  t.requires_human_approval,
  t.approval_gate,
  t.preceded_by_steps,
  calc_workflow_steps_execution_actor_type(t.workflow_step_id) AS execution_actor_type,
  calc_workflow_steps_assigned_role_department(t.workflow_step_id) AS assigned_role_department,
  calc_workflow_steps_approval_gate_escalation_threshold_hours(t.workflow_step_id) AS approval_gate_escalation_threshold_hours,
  t.step_transitions_from_step,
  t.step_transitions_to_step,
  t.workflow_artifacts
FROM workflow_steps t;

CREATE OR REPLACE VIEW vw_approvals WITH (security_invoker = ON) AS
SELECT
  t.approval_id,
  calc_approvals_name(t.approval_id) AS name,
  t.display_name,
  t.workflow_steps,
  t.escalation_threshold_hours,
  calc_approvals_workflow_from_workflow_steps(t.approval_id) AS workflow_from_workflow_steps,
  calc_approvals_assigned_role_from_workflow_steps(t.approval_id) AS assigned_role_from_workflow_steps,
  calc_approvals_sequence_position_from_workflow_steps(t.approval_id) AS sequence_position_from_workflow_steps,
  calc_approvals_requires_human_approval_from_workflow_steps(t.approval_id) AS requires_human_approval_from_workflow_steps
FROM approvals t;

CREATE OR REPLACE VIEW vw_precedes_steps WITH (security_invoker = ON) AS
SELECT
  t.precedes_step_id,
  t.name,
  calc_precedes_steps_display_name(t.precedes_step_id) AS display_name,
  t.step_number,
  t.workflow_step
FROM precedes_steps t;

CREATE OR REPLACE VIEW vw_roles WITH (security_invoker = ON) AS
SELECT
  t.role_id,
  calc_roles_name(t.role_id) AS name,
  t.display_name,
  t.label,
  t.comment,
  t.filled_by_human_agent,
  t.filled_by_ai_agent,
  t.filled_by_automated_pipeline,
  t.owned_by,
  t.delegates_to,
  calc_roles_workflow_steps(t.role_id) AS workflow_steps,
  t.from_delegates_to,
  calc_roles_all_linked_workflow_steps(t.role_id) AS all_linked_workflow_steps,
  calc_roles_distinct_workflows_for_linked_steps(t.role_id) AS distinct_workflows_for_linked_steps,
  t.workflow_artifacts
FROM roles t;

CREATE OR REPLACE VIEW vw_departments WITH (security_invoker = ON) AS
SELECT
  t.department_id,
  calc_departments_name(t.department_id) AS name,
  t.title,
  t.display_name,
  calc_departments_roles(t.department_id) AS roles,
  calc_departments_all_owned_roles(t.department_id) AS all_owned_roles,
  calc_departments_all_related_workflow_steps(t.department_id) AS all_related_workflow_steps,
  calc_departments_all_distinct_workflows_for_owned_roles(t.department_id) AS all_distinct_workflows_for_owned_roles
FROM departments t;

CREATE OR REPLACE VIEW vw_human_agents WITH (security_invoker = ON) AS
SELECT
  t.human_agent_id,
  t.name,
  t.display_name,
  t.mbox,
  t.roles,
  calc_human_agents_all_linked_roles(t.human_agent_id) AS all_linked_roles,
  calc_human_agents_all_related_workflow_steps(t.human_agent_id) AS all_related_workflow_steps,
  calc_human_agents_all_distinct_workflows_for_linked_roles(t.human_agent_id) AS all_distinct_workflows_for_linked_roles,
  t.workflow_artifacts
FROM human_agents t;

CREATE OR REPLACE VIEW vw_ai_agents WITH (security_invoker = ON) AS
SELECT
  t.ai_agent_id,
  t.name,
  t.title,
  t.display_name,
  t.model_version,
  t.roles,
  t.workflow_artifacts
FROM ai_agents t;

CREATE OR REPLACE VIEW vw_automated_pipelines WITH (security_invoker = ON) AS
SELECT
  t.automated_pipeline_id,
  t.name,
  t.description,
  t.display_name,
  t.roles,
  t.workflow_artifacts
FROM automated_pipelines t;

CREATE OR REPLACE VIEW vw_step_transitions WITH (security_invoker = ON) AS
SELECT
  t.step_transition_id,
  t.name,
  t.from_step,
  t.to_step,
  calc_step_transitions_workflow_from_from_step(t.step_transition_id) AS workflow_from_from_step
FROM step_transitions t;

CREATE OR REPLACE VIEW vw_workflow_artifacts WITH (security_invoker = ON) AS
SELECT
  t.workflow_artifact_id,
  t.artifact_name,
  t.produced_by_step,
  calc_workflow_artifacts_workflow_from_produced_by_step(t.workflow_artifact_id) AS workflow_from_produced_by_step,
  t.attributed_role,
  t.attributed_human_agent,
  t.attributed_ai_agent,
  t.attributed_pipeline,
  t.derived_from_artifact,
  t.artifact_description,
  t.artifact_file,
  t.from_field_derived_from_artifact
FROM workflow_artifacts t;

CREATE OR REPLACE VIEW vw_erb_versions WITH (security_invoker = ON) AS
SELECT
  t.erb_version_id,
  t.base_id,
  t.name,
  t.message,
  t.notes,
  t.commit_date,
  t.is_published
FROM erb_versions t;

CREATE OR REPLACE VIEW vw_erb_customizations WITH (security_invoker = ON) AS
SELECT
  t.erb_customization_id,
  t.name,
  t.title,
  t.sql_code,
  t.sql_target,
  t.customization_type
FROM erb_customizations t;

