-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 8
-- ============================================================================

CREATE OR REPLACE VIEW vw_app_users WITH (security_invoker = ON) AS
SELECT
  t.app_user_id,
  t.name,
  t.email_address,
  t.role,
  t.is_active,
  calc_app_users_widgets(t.app_user_id) AS widgets,
  t.notes
FROM app_users t;

CREATE OR REPLACE VIEW vw_shapes WITH (security_invoker = ON) AS
SELECT
  t.shape_id,
  t.name,
  calc_shapes_sides(t.shape_id) AS sides,
  calc_shapes_how_many_sides(t.shape_id) AS how_many_sides,
  calc_shapes_is_rectangle(t.shape_id) AS is_rectangle,
  calc_shapes_is_triangle(t.shape_id) AS is_triangle,
  calc_shapes_is_right_triangle(t.shape_id) AS is_right_triangle,
  calc_shapes_sum_of_internal_angles(t.shape_id) AS sum_of_internal_angles,
  calc_shapes_max_angle(t.shape_id) AS max_angle,
  calc_shapes_hypotenuse_length_squared(t.shape_id) AS hypotenuse_length_squared,
  calc_shapes_non_hypotenuse_sides_squared(t.shape_id) AS non_hypotenuse_sides_squared,
  calc_shapes_pythagorean_theorem_holds(t.shape_id) AS pythagorean_theorem_holds
FROM shapes t;

CREATE OR REPLACE VIEW vw_sides WITH (security_invoker = ON) AS
SELECT
  t.side_id,
  calc_sides_name(t.side_id) AS name,
  calc_sides_shape_sides(t.side_id) AS shape_sides,
  t.label,
  calc_sides_is_rectangle(t.side_id) AS is_rectangle,
  calc_sides_is_triangle(t.side_id) AS is_triangle,
  calc_sides_is_right_triangle(t.side_id) AS is_right_triangle,
  calc_sides_is_hypotenuse(t.side_id) AS is_hypotenuse,
  calc_sides_status_of_theorem(t.side_id) AS status_of_theorem,
  calc_sides_pythagorean_theorem_holds(t.side_id) AS pythagorean_theorem_holds,
  calc_sides_length_squared(t.side_id) AS length_squared,
  calc_sides_hypotenuse_length_squared(t.side_id) AS hypotenuse_length_squared,
  calc_sides_non_hypotenuse_length_squared(t.side_id) AS non_hypotenuse_length_squared,
  calc_sides_previous_side_length(t.side_id) AS previous_side_length,
  t.length,
  calc_sides_next_length(t.side_id) AS next_length,
  calc_sides_previous_angle(t.side_id) AS previous_angle,
  t.angle,
  calc_sides_next_angle(t.side_id) AS next_angle,
  t.previous_side,
  t.next_side,
  t.shape,
  calc_sides_previous_label(t.side_id) AS previous_label,
  calc_sides_next_label(t.side_id) AS next_label
FROM sides t;

CREATE OR REPLACE VIEW vw_widgets WITH (security_invoker = ON) AS
SELECT
  t.widget_id,
  t.name,
  t.appuser,
  calc_widgets_name_from_appuser(t.widget_id) AS name_from_appuser,
  calc_widgets_email_address_from_appuser(t.widget_id) AS email_address_from_appuser,
  calc_widgets_role_from_appuser(t.widget_id) AS role_from_appuser,
  t.color
FROM widgets t;

CREATE OR REPLACE VIEW vw_erb_versions WITH (security_invoker = ON) AS
SELECT
  t.erb_version_id,
  calc_erb_versions_pk(t.erb_version_id) AS pk,
  t.base_id,
  t.name,
  t.message,
  t.notes,
  t.commit_date,
  t.is_published
FROM erb_versions t;

CREATE OR REPLACE VIEW vw_erb_customizations WITH (security_invoker = ON) AS
SELECT
  t.erb_customization_id,
  t.name,
  t.title,
  t.sql_code,
  t.sql_target,
  t.customization_type
FROM erb_customizations t;

CREATE OR REPLACE VIEW vw_magic_link_integration WITH (security_invoker = ON) AS
SELECT
  t.magic_link_integration_id,
  t.name,
  t.enabled,
  t.tenant_id,
  t.public_key_pem,
  t.user_table_name,
  t.email_field,
  t.role_field,
  t.is_active_field,
  t.user_id_field,
  t.allowed_algorithms,
  t.require_tenant_binding,
  t.use_email_dag_pattern
FROM magic_link_integration t;

