-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

INSERT INTO app_users (app_user_id, name, email_address, role, is_active, notes)
VALUES ('ej', 'EJ', 'ej@ssot.me', 'Admin', TRUE, '');

INSERT INTO app_users (app_user_id, name, email_address, role, is_active, notes)
VALUES ('bob', 'Bob', 'bob@ssot.me', 'Mathemetician', TRUE, '');

INSERT INTO app_users (app_user_id, name, email_address, role, is_active, notes)
VALUES ('andy', 'Andy', 'guest@ssot.me', 'Guest', TRUE, '');

INSERT INTO app_users (app_user_id, name, email_address, role, is_active, notes)
VALUES ('bob2', 'Bob2', 'bob@ssot.me', '', FALSE, '');

INSERT INTO shapes (shape_id, name)
VALUES ('shape1', 'Shape1');

INSERT INTO shapes (shape_id, name)
VALUES ('shape2', 'Shape2');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape1-side-a', 'A', 5, 45, 'shape1-side-c', 'shape1-side-b', 'shape1');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape1-side-b', 'B', 4, 45, 'shape1-side-a', 'shape1-side-c', 'shape1');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape1-side-c', 'C', 3, 90, 'shape1-side-b', 'shape1-side-a', 'shape1');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape2-side-a', 'A', 2, 90, 'shape2-side-d', 'shape2-side-b', 'shape2');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape2-side-b', 'B', 2, 90, 'shape2-side-a', 'shape2-side-c', 'shape2');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape2-side-c', 'C', 2, 90, 'shape2-side-b', 'shape2-side-d', 'shape2');

INSERT INTO sides (side_id, label, length, angle, previous_side, next_side, shape)
VALUES ('shape2-side-d', 'D', 2, 90, 'shape2-side-c', 'shape2-side-a', 'shape2');

INSERT INTO widgets (widget_id, name, appuser, color)
VALUES ('widget1', 'widget1', 'bob', 'Blue');

INSERT INTO widgets (widget_id, name, appuser, color)
VALUES ('widget2', 'widget2', 'bob', 'pink');

INSERT INTO widgets (widget_id, name, appuser, color)
VALUES ('widget3', 'widget3', 'andy', '');

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('b0e261e6-9ded-4ed0-817a-12a82a538201-version-2026-02-06-22-18-34', 'b0e261e6-9ded-4ed0-817a-12a82a538201', 'Version 2026-02-06 22:18:34', 'fixed custom RLS policies.', '', '2026-02-06', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('b0e261e6-9ded-4ed0-817a-12a82a538201-version-2026-02-07-01-50-20', 'b0e261e6-9ded-4ed0-817a-12a82a538201', 'Version 2026-02-07 01:50:20', 'Trying to get data in as well.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('b0e261e6-9ded-4ed0-817a-12a82a538201-version-2026-02-07-01-54-24', 'b0e261e6-9ded-4ed0-817a-12a82a538201', 'Version 2026-02-07 01:54:24', 'Updated base again.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('e7b6e278-92b8-4a76-a3bf-d2b1183d1c77-version-2026-02-07-02-00-40', 'e7b6e278-92b8-4a76-a3bf-d2b1183d1c77', 'Version 2026-02-07 02:00:40', 'Trying to get data in the db.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('e7b6e278-92b8-4a76-a3bf-d2b1183d1c77-version-2026-02-07-02-18-06', 'e7b6e278-92b8-4a76-a3bf-d2b1183d1c77', 'Version 2026-02-07 02:18:06', 'Added app users.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('e7b6e278-92b8-4a76-a3bf-d2b1183d1c77-version-2026-02-07-02-27-57', 'e7b6e278-92b8-4a76-a3bf-d2b1183d1c77', 'Version 2026-02-07 02:27:57', 'Added AppUsers.IsActive', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('e7b6e278-92b8-4a76-a3bf-d2b1183d1c77-version-2026-02-07-22-46-12', 'e7b6e278-92b8-4a76-a3bf-d2b1183d1c77', 'Version 2026-02-07 22:46:12', 'trying new admin/anon users.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('e7b6e278-92b8-4a76-a3bf-d2b1183d1c77-version-2026-02-07-22-47-11', 'e7b6e278-92b8-4a76-a3bf-d2b1183d1c77', 'Version 2026-02-07 22:47:11', 'added admin/anon users.', '', '2026-02-07', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-08-03-55-18', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-08 03:55:18', 'fixing auth', '', '2026-02-08', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-09-06-07-44', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-09 06:07:44', 'temp 4', '', '2026-02-09', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-09-06-14-38', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-09 06:14:38', 'added ownership records to widgets', '', '2026-02-09', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-09-07-22-15', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-09 07:22:15', 'test preserving builders', '', '2026-02-09', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-09-07-41-26', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-09 07:41:26', 'preserves policies now?', '', '2026-02-09', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-09-07-46-04', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-09 07:46:04', 'added color to widgets', '', '2026-02-09', FALSE);

INSERT INTO erb_versions (erb_version_id, base_id, name, message, notes, commit_date, is_published)
VALUES ('f4cefffd-29c7-4dc6-8b5b-2142c62a475c-version-2026-02-11-00-40-18', 'f4cefffd-29c7-4dc6-8b5b-2142c62a475c', 'Version 2026-02-11 00:40:18', 'added another b ob.', '', '2026-02-11', FALSE);

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03a-customize-schema-sql', '03a-customize-schema.sql', 'Customize Schema', '-- ============================================================================
-- CUSTOMIZE SCHEMA - User-defined tables and schema modifications
-- ============================================================================
-- This file is for YOUR custom schema changes that should persist across
-- regeneration of the base ERB files.
--
-- USE THIS FILE FOR:
--   - Additional tables not defined in the rulebook
--   - Extra columns on existing tables (ALTER TABLE)
--   - Custom indexes for performance tuning
--   - Custom constraints or triggers
--
-- IMPORTANT:
--   - This file runs AFTER 01-drop-and-create-tables.sql
--   - The base tables already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom schema changes go here:
', 'Postgres', 'Schema');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03b-customize-functions-sql', '03b-customize-functions.sql', 'Customize Functions', '-- ============================================================================
-- CUSTOMIZE FUNCTIONS - User-defined calculation functions
-- ============================================================================
-- This file is for YOUR custom PostgreSQL functions that should persist
-- across regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 02-create-functions.sql
--   - Base ERB calc functions already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom functions go here:
CREATE OR REPLACE FUNCTION public.calc_shapes_hypotenuse_length_squared(p_shape_id text)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN ((SELECT COALESCE(MAX(calc_sides_hypotenuse_length_squared(side_id)), 0) FROM sides WHERE shape = p_shape_id));
END;
$function$;


CREATE OR REPLACE FUNCTION public.calc_sides_length_squared(p_side_id text)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN ((SELECT length FROM sides WHERE side_id = p_side_id) * (SELECT length FROM sides WHERE side_id = p_side_id));
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_shapes_hypotenuse_length_squared(p_shape_id text)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN ((SELECT COALESCE(MAX(calc_sides_hypotenuse_length_squared(side_id)), 0) FROM sides WHERE shape = p_shape_id));
END;
$function$;
', 'Postgres', 'Functions');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03c-customize-views-sql', '03c-customize-views.sql', 'Customize Views', '-- ============================================================================
-- CUSTOMIZE VIEWS - User-defined views and view extensions
-- ============================================================================
-- This file is for YOUR custom views that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 03-create-views.sql
--   - All base vw_* views already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom views go here:
', 'Postgres', 'Views');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03d-customize-rls-sql', '03d-customize-rls.sql', 'Customize Policies (RLS)', '-- ============================================================================
-- CUSTOMIZE POLICIES - User-defined Row Level Security policies
-- ============================================================================
-- This file is for YOUR custom RLS policies that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 04-create-policies.sql
--   - Base RLS policies already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom policies go here:
', 'Postgres', 'RLS');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03e-customize-data-sql', '03e-customize-data.sql', 'Customize Data (Seeds / Migrations)', '-- ============================================================================
-- CUSTOMIZE DATA - User-defined seed data and data migrations
-- ============================================================================
-- This file is for YOUR custom seed data that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 05-insert-data.sql
--   - Base seed data already exists when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom data inserts go here:
', 'Postgres', 'Data');

INSERT INTO magic_link_integration (magic_link_integration_id, name, enabled, tenant_id, public_key_pem, user_table_name, email_field, role_field, is_active_field, user_id_field, allowed_algorithms, require_tenant_binding, use_email_dag_pattern)
VALUES ('magic-link-config', 'Magic Link Config', TRUE, 'c03e9d56-9525-47dd-9ee1-2f2a20383048', '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2XyDcVliu0wjQjDY1Rez
/krdzYL3v4TXCJbYu2V1EkrKlVjO+ZGCIHu0yMAw5A+cUMm5cXtYyIXNln6tCg0M
LHcNVrSDm5QuQSUuGP/SVrgSUItyrGfLZOwl+kYXgMmle4t11ecVhkaVARisBcRz
Irh9ofSNtLR6UlJzKH4uFFswId5HrgwMCbart2YcrA7lrEt1hqASZ7pPPX6/i771
97VqSf+clLX3Wq5VwyrtC9taTiVZrN/OhtWbSAkUX+NMkCc57MN4CcjP3/8JXbjv
4L5ExZOpc14zRhOnOnC0cHRX475WoJbjI3+EfYDjaNrV6MVd444S/8HOOz3D8Pki
XwIDAQAB
-----END PUBLIC KEY-----', 'app_users', 'email_address', 'role', 'is_active', '', 'RS256', TRUE, TRUE);

