#!/usr/bin/env python3
"""
Shared functions for ERB execution substrate generators.
All inject-into-*.py scripts use these common utilities.
"""

import json
import os
from pathlib import Path
from datetime import datetime


def get_rulebook_path():
    """Get the path to the effortless-rulebook.json file.

    Scripts run from /execution-substrates/{candidate}/ so the rulebook
    is at ../../effortless-rulebook/effortless-rulebook.json
    """
    return Path("../../effortless-rulebook/effortless-rulebook.json")


def load_rulebook():
    """Load and parse the effortless-rulebook.json file."""
    rulebook_path = get_rulebook_path()

    if not rulebook_path.exists():
        raise FileNotFoundError(f"Rulebook not found at {rulebook_path}")

    with open(rulebook_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def ensure_output_folder():
    """Ensure the current working directory exists (it should, since we run from there)."""
    cwd = Path.cwd()
    cwd.mkdir(parents=True, exist_ok=True)
    return cwd


def write_readme(candidate_name, description=None, technology=None):
    """Write a placeholder README.md for the execution substrate.

    Args:
        candidate_name: Name of the target format/substrate (e.g., 'python', 'owl')
        description: Optional description, defaults to a placeholder message
        technology: Optional technology section explaining the format/substrate
    """
    output_folder = ensure_output_folder()
    readme_path = output_folder / "README.md"

    if description is None:
        description = f"Placeholder for {candidate_name} generation from the Effortless Rulebook."

    # Build technology section if provided
    technology_section = ""
    if technology:
        technology_section = f"\n## Technology\n\n{technology}\n"

    content = f"""# {candidate_name.title()} Execution Substrate

{description}
{technology_section}
## Status

This is a placeholder generated by the ERB orchestration system.

## Source

Generated from: `effortless-rulebook/effortless-rulebook.json`

"""

    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Created {readme_path}")
    return readme_path


def get_candidate_name_from_cwd():
    """Extract the candidate name from the current working directory.

    Assumes we're running from /execution-substrates/{candidate}/
    """
    return Path.cwd().name


def clean_generated_files(generated_files: list, substrate_name: str = None):
    """Remove generated files from a substrate directory.

    Args:
        generated_files: List of filenames (relative to cwd) to remove
        substrate_name: Optional name for logging (defaults to cwd name)

    Returns:
        List of files that were successfully removed
    """
    if substrate_name is None:
        substrate_name = get_candidate_name_from_cwd()

    cwd = Path.cwd()
    removed = []

    print(f"Cleaning generated files for {substrate_name}...")

    for filename in generated_files:
        file_path = cwd / filename
        if file_path.exists():
            try:
                file_path.unlink()
                print(f"  Removed: {filename}")
                removed.append(filename)
            except Exception as e:
                print(f"  Failed to remove {filename}: {e}")
        else:
            print(f"  Skipped (not found): {filename}")

    if removed:
        print(f"Cleaned {len(removed)} file(s)")
    else:
        print("No files to clean")

    return removed


def handle_clean_arg(generated_files: list, description: str = None):
    """Check for --clean argument and perform cleanup if requested.

    Args:
        generated_files: List of filenames to remove when cleaning
        description: Optional description to display

    Returns:
        True if --clean was handled (script should exit), False otherwise
    """
    import sys

    if '--clean' in sys.argv:
        substrate_name = get_candidate_name_from_cwd()
        if description:
            print(f"\n{description}\n")
        print(f"=" * 60)
        print(f"CLEAN MODE: {substrate_name.upper()}")
        print(f"=" * 60)
        clean_generated_files(generated_files, substrate_name)
        return True

    return False


# =============================================================================
# ENTITY DISCOVERY FUNCTIONS
# =============================================================================
# These functions discover entities, schemas, and computed columns from the
# rulebook. They enable multi-entity processing across all substrates.
# =============================================================================

import re


def to_snake_case(name: str) -> str:
    """Convert PascalCase to snake_case: UserAccounts -> user_accounts

    Also handles fields with existing underscores: Bio_HockettScore -> bio_hockett_score
    """
    # Use [^_] to avoid doubling underscores when input already has them
    s1 = re.sub('([^_])([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def to_pascal_case(name: str) -> str:
    """Convert snake_case to PascalCase: user_accounts -> UserAccounts"""
    return ''.join(word.capitalize() for word in name.split('_'))


def discover_entities(rulebook: dict) -> list:
    """
    Discover all entities from the rulebook.
    Entities are top-level keys that have a 'schema' array.
    Returns list of entity names in PascalCase (as they appear in rulebook).
    """
    entities = []
    skip_keys = {'$schema', 'model_name', 'Description', '_meta'}

    for key, value in rulebook.items():
        if key in skip_keys:
            continue
        if isinstance(value, dict) and 'schema' in value:
            entities.append(key)

    return entities


def get_entity_schema(rulebook: dict, entity_name: str) -> list:
    """
    Get the schema array for an entity.
    Handles both PascalCase and snake_case entity names.
    """
    # Try direct lookup first
    if entity_name in rulebook:
        return rulebook[entity_name].get('schema', [])

    # Try converting from snake_case to PascalCase
    pascal_name = to_pascal_case(entity_name)
    if pascal_name in rulebook:
        return rulebook[pascal_name].get('schema', [])

    # Try converting from PascalCase to snake_case and look up
    snake_name = to_snake_case(entity_name)
    for key in rulebook:
        if to_snake_case(key) == snake_name:
            return rulebook[key].get('schema', [])

    return []


def get_entity_data(rulebook: dict, entity_name: str) -> list:
    """
    Get the data array for an entity.
    Handles both PascalCase and snake_case entity names.
    """
    # Try direct lookup first
    if entity_name in rulebook:
        return rulebook[entity_name].get('data', [])

    # Try converting from snake_case to PascalCase
    pascal_name = to_pascal_case(entity_name)
    if pascal_name in rulebook:
        return rulebook[pascal_name].get('data', [])

    # Try converting from PascalCase to snake_case and look up
    snake_name = to_snake_case(entity_name)
    for key in rulebook:
        if to_snake_case(key) == snake_name:
            return rulebook[key].get('data', [])

    return []


def discover_primary_key(rulebook: dict, entity_name: str) -> str:
    """
    Discover the primary key for an entity.
    Returns the first non-nullable field, or first field ending in 'Id'.
    """
    schema = get_entity_schema(rulebook, entity_name)

    # First try: find first non-nullable field
    for field in schema:
        if field.get('nullable') == False:
            return to_snake_case(field['name'])

    # Second try: find first field ending in 'Id'
    for field in schema:
        if field['name'].endswith('Id'):
            return to_snake_case(field['name'])

    # Fallback: first field
    if schema:
        return to_snake_case(schema[0]['name'])

    return None


def discover_computed_columns(rulebook: dict, entity_name: str) -> list:
    """
    Discover computed columns for an entity.
    Returns list of snake_case column names where type == "calculated".
    """
    schema = get_entity_schema(rulebook, entity_name)

    computed = []
    for field in schema:
        if field.get('type') == 'calculated':
            computed.append(to_snake_case(field['name']))

    return computed


def get_calculated_fields(schema: list) -> list:
    """
    Extract all calculated fields from a schema.
    Returns list of field dicts where type is "calculated" and formula exists.

    Note: "lookup" type fields are NOT included here - they use INDEX/MATCH formulas
    that require cross-table access and are handled separately by compute_lookups().
    """
    return [
        field for field in schema
        if field.get('type') == 'calculated' and field.get('formula')
    ]


def get_raw_fields(schema: list) -> list:
    """Extract all raw fields from a schema."""
    return [field for field in schema if field.get('type') == 'raw']


def get_aggregation_fields(schema: list) -> list:
    """Extract all aggregation fields from a schema."""
    return [field for field in schema if field.get('type') == 'aggregation']


def get_lookup_fields(schema: list) -> list:
    """Extract all lookup fields from a schema (INDEX/MATCH formulas)."""
    return [field for field in schema if field.get('type') == 'lookup' and field.get('formula')]


# =============================================================================
# INDEX/MATCH LOOKUP COMPUTATION
# =============================================================================
# These functions compute lookup fields (INDEX/MATCH) by loading related data
# from the testing/blank-tests or answer-keys directory.
# =============================================================================

def parse_index_match_formula(formula: str) -> tuple:
    """
    Parse an INDEX/MATCH formula to extract the lookup components.

    Formula format: =INDEX(Table!{{FieldToReturn}}, MATCH(CurrentTable!{{KeyField}}, Table!{{PrimaryKeyField}}, 0))
    Example: =INDEX(Workflows!{{Title}}, MATCH(WorkflowSteps!{{IsStepOf}}, Workflows!{{WorkflowId}}, 0))

    Returns: (lookup_table, return_field, key_field, pk_field) or (None, None, None, None) if not parseable
    """
    import re
    # Match pattern: INDEX(Table!{{Field}}, MATCH(Table!{{Field}}, Table!{{Field}}, 0))
    pattern = r'=INDEX\((\w+)!\{\{(\w+)\}\},\s*MATCH\(\w+!\{\{(\w+)\}\},\s*(\w+)!\{\{(\w+)\}\},\s*0\)\)'
    match = re.match(pattern, formula)
    if match:
        lookup_table = match.group(1)    # e.g., "Workflows"
        return_field = match.group(2)    # e.g., "Title"
        key_field = match.group(3)       # e.g., "IsStepOf"
        # pk_table = match.group(4)      # Should match lookup_table
        pk_field = match.group(5)        # e.g., "WorkflowId"
        return (lookup_table, return_field, key_field, pk_field)
    return (None, None, None, None)


def compute_lookups(records: list, entity_name: str, rulebook: dict, project_root: Path) -> list:
    """
    Compute lookup fields (INDEX/MATCH) for a list of records.

    This function identifies lookup fields in the schema, loads related data,
    and computes the lookup values by matching keys and returning indexed values.

    Args:
        records: List of records to update with lookup values
        entity_name: Name of the entity (PascalCase or snake_case)
        rulebook: The loaded rulebook dictionary
        project_root: Path to the project root for loading related data

    Returns:
        Updated list of records with lookup fields populated
    """
    schema = get_entity_schema(rulebook, entity_name)
    lookup_fields = get_lookup_fields(schema)

    if not lookup_fields:
        return records

    # Cache for loaded related data
    related_data_cache = {}

    for field in lookup_fields:
        field_name = field.get('name')
        formula = field.get('formula', '')
        snake_field_name = to_snake_case(field_name)

        # Parse the INDEX/MATCH formula
        lookup_table, return_field, key_field, pk_field = parse_index_match_formula(formula)

        if not lookup_table:
            # Not a valid INDEX/MATCH formula, skip
            continue

        # Load related table data
        if lookup_table not in related_data_cache:
            related_data_cache[lookup_table] = load_related_data(project_root, lookup_table)

        related_records = related_data_cache[lookup_table]
        snake_return_field = to_snake_case(return_field)
        snake_key_field = to_snake_case(key_field)
        snake_pk_field = to_snake_case(pk_field)

        # Build a lookup map: pk_value -> return_value
        lookup_map = {}
        for related_record in related_records:
            pk_value = related_record.get(snake_pk_field)
            if pk_value is not None:
                lookup_map[pk_value] = related_record.get(snake_return_field)

        # Update each record with the lookup value
        for record in records:
            key_value = record.get(snake_key_field)
            if key_value is not None and key_value in lookup_map:
                record[snake_field_name] = lookup_map[key_value]
            else:
                # No match found - leave as None or empty string
                record[snake_field_name] = None

    return records


# =============================================================================
# AGGREGATION COMPUTATION
# =============================================================================
# These functions compute aggregation fields (COUNTIFS, SUMIFS, etc.) by
# loading related data from the testing/blank-tests directory.
# =============================================================================

def parse_countifs_formula(formula: str) -> tuple:
    """
    Parse a COUNTIFS formula to extract the related table, lookup field, and match field.

    Formula format: =COUNTIFS(RelatedTable!{{LookupField}}, CurrentTable!{{MatchField}})
    Example: =COUNTIFS(WorkflowSteps!{{Workflow}}, Workflows!{{WorkflowId}})

    Returns: (related_table, lookup_field, match_field) or (None, None, None) if not parseable
    """
    import re
    # Match pattern: COUNTIFS(Table!{{Field}}, Table!{{Field}})
    pattern = r'=COUNTIFS\((\w+)!\{\{(\w+)\}\},\s*\w+!\{\{(\w+)\}\}\)'
    match = re.match(pattern, formula)
    if match:
        related_table = match.group(1)  # e.g., "WorkflowSteps"
        lookup_field = match.group(2)   # e.g., "Workflow"
        match_field = match.group(3)    # e.g., "WorkflowId"
        return (related_table, lookup_field, match_field)
    return (None, None, None)


def parse_sumifs_formula(formula: str) -> tuple:
    """
    Parse a SUMIFS formula to extract the related table, sum field, criteria field, and match field.

    Formula format: =SUMIFS(RelatedTable!{{SumField}}, RelatedTable!{{CriteriaField}}, CurrentTable!{{MatchField}})
    Example: =SUMIFS(WorkflowSteps!{{Name}}, WorkflowSteps!{{AssignedRole}}, Roles!{{RoleId}})

    Returns: (related_table, sum_field, criteria_field, match_field) or (None, None, None, None) if not parseable
    """
    import re
    # Match pattern: SUMIFS(Table!{{Field}}, Table!{{Field}}, Table!{{Field}})
    pattern = r'=SUMIFS\((\w+)!\{\{(\w+)\}\},\s*(\w+)!\{\{(\w+)\}\},\s*\w+!\{\{(\w+)\}\}\)'
    match = re.match(pattern, formula)
    if match:
        related_table = match.group(1)  # e.g., "WorkflowSteps"
        sum_field = match.group(2)      # e.g., "Name"
        # criteria_table = match.group(3) - should match related_table
        criteria_field = match.group(4) # e.g., "AssignedRole"
        match_field = match.group(5)    # e.g., "RoleId"
        return (related_table, sum_field, criteria_field, match_field)
    return (None, None, None, None)


def load_related_data(project_root: Path, related_table: str) -> list:
    """
    Load data from testing/answer-keys for a related table.

    Prefers answer-keys (which have computed fields) over blank-tests.
    This is necessary for aggregations that reference calculated fields
    in related tables (e.g., SUMIFS on a computed Name field).

    Args:
        project_root: Path to the project root
        related_table: PascalCase name of the related table

    Returns:
        List of records from the related table's data file
    """
    snake_name = to_snake_case(related_table)

    # Prefer answer-keys (has computed fields) over blank-tests
    answer_keys_path = project_root / "testing" / "answer-keys" / f"{snake_name}.json"
    if answer_keys_path.exists():
        with open(answer_keys_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    # Fall back to blank-tests
    blank_tests_path = project_root / "testing" / "blank-tests" / f"{snake_name}.json"
    if blank_tests_path.exists():
        with open(blank_tests_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    return []


def estimate_llm_time(rulebook: dict, seconds_per_unit: float = 2.0) -> str:
    """
    Estimate how long LLM-based testing will take based on rulebook size.

    Calculation: sum of (fields * rows) for each entity
    Assumes each unit takes ~seconds_per_unit seconds.
    Returns time rounded UP to nearest 15 seconds in "m:ss" format.

    Args:
        rulebook: The loaded rulebook dictionary
        seconds_per_unit: Estimated seconds per field*row unit (default 2.0)

    Returns:
        Formatted string like "2:30" (2 minutes, 30 seconds)
    """
    import math
    entities = discover_entities(rulebook)
    total_units = 0

    for entity in entities:
        schema = get_entity_schema(rulebook, entity)
        data = get_entity_data(rulebook, entity)
        num_fields = len(schema)
        num_rows = len(data)
        total_units += num_fields * num_rows

    # Calculate seconds and round UP to nearest 15
    total_seconds = int(total_units * seconds_per_unit)
    rounded_seconds = math.ceil(total_seconds / 15) * 15

    # Ensure at least 15 seconds
    rounded_seconds = max(15, rounded_seconds)

    # Format as m:ss
    minutes = rounded_seconds // 60
    seconds = rounded_seconds % 60
    return f"{minutes}:{seconds:02d}"


def compute_aggregations(records: list, entity_name: str, rulebook: dict, project_root: Path) -> list:
    """
    Compute aggregation fields for a list of records.

    This function identifies aggregation fields in the schema, loads related data,
    and computes the aggregated values (e.g., COUNTIFS, SUMIFS).

    Args:
        records: List of records to update with aggregation values
        entity_name: Name of the entity (PascalCase or snake_case)
        rulebook: The loaded rulebook dictionary
        project_root: Path to the project root for loading related data

    Returns:
        Updated list of records with aggregation fields populated
    """
    schema = get_entity_schema(rulebook, entity_name)
    agg_fields = get_aggregation_fields(schema)

    if not agg_fields:
        return records

    # Cache for loaded related data
    related_data_cache = {}

    for field in agg_fields:
        field_name = field.get('name')
        formula = field.get('formula', '')
        snake_field_name = to_snake_case(field_name)

        # Try COUNTIFS first
        related_table, lookup_field, match_field = parse_countifs_formula(formula)

        if related_table:
            # Handle COUNTIFS - count matching records
            if related_table not in related_data_cache:
                related_data_cache[related_table] = load_related_data(project_root, related_table)

            related_records = related_data_cache[related_table]
            snake_lookup_field = to_snake_case(lookup_field)
            snake_match_field = to_snake_case(match_field)

            # Build a count map: match_value -> count
            count_map = {}
            for related_record in related_records:
                lookup_value = related_record.get(snake_lookup_field)
                if lookup_value is not None:
                    count_map[lookup_value] = count_map.get(lookup_value, 0) + 1

            # Update each record with the aggregation value
            for record in records:
                match_value = record.get(snake_match_field)
                if match_value is not None:
                    record[snake_field_name] = count_map.get(match_value, 0)
                else:
                    record[snake_field_name] = 0
            continue

        # Try SUMIFS
        related_table, sum_field, criteria_field, match_field = parse_sumifs_formula(formula)

        if related_table:
            # Handle SUMIFS - collect and concatenate matching values
            if related_table not in related_data_cache:
                related_data_cache[related_table] = load_related_data(project_root, related_table)

            related_records = related_data_cache[related_table]
            snake_sum_field = to_snake_case(sum_field)
            snake_criteria_field = to_snake_case(criteria_field)
            snake_match_field = to_snake_case(match_field)

            # Check if this is a "distinct" aggregation (deduplication needed)
            is_distinct = 'distinct' in field_name.lower()

            # Find the primary key field for related records (for lookup by ID)
            related_pk_field = to_snake_case(related_table[:-1] + 'Id')  # e.g., "Roles" -> "role_id"
            # Build a lookup map: pk_value -> record
            pk_to_record = {}
            for rec in related_records:
                pk_val = rec.get(related_pk_field)
                if pk_val:
                    pk_to_record[pk_val] = rec

            # Find relationship field in current schema that points to related table
            # This determines the ordering
            relationship_field = None
            for f in schema:
                if f.get('type') == 'relationship' and f.get('RelatedTo') == related_table:
                    relationship_field = to_snake_case(f.get('name'))
                    break

            # Update each record with the aggregation value
            for record in records:
                match_value = record.get(snake_match_field)
                values = []
                has_any_match = False

                # If we have a relationship field, use its order
                if relationship_field and relationship_field in record and record[relationship_field]:
                    rel_ids = [rid.strip() for rid in str(record[relationship_field]).split(',') if rid.strip()]
                    for rel_id in rel_ids:
                        rel_rec = pk_to_record.get(rel_id)
                        if rel_rec:
                            # Check if criteria matches (for chained aggregations)
                            criteria_value = rel_rec.get(snake_criteria_field)
                            if criteria_value == match_value:
                                has_any_match = True
                                sum_value = rel_rec.get(snake_sum_field)
                                # Include value (or empty string for 0/"" values)
                                if sum_value is not None and sum_value != '' and sum_value != 0:
                                    str_value = str(sum_value)
                                    if is_distinct:
                                        if str_value not in values:
                                            values.append(str_value)
                                    else:
                                        values.append(str_value)
                                else:
                                    # Include empty placeholder for 0 or "" values
                                    values.append('')
                else:
                    # No relationship field - fall back to sequence_position sorting
                    sorted_records = sorted(
                        related_records,
                        key=lambda r: r.get('sequence_position', 0) if r.get('sequence_position') is not None else 0
                    )
                    for related_record in sorted_records:
                        criteria_value = related_record.get(snake_criteria_field)
                        if criteria_value == match_value:
                            has_any_match = True
                            sum_value = related_record.get(snake_sum_field)
                            if sum_value is not None and sum_value != '' and sum_value != 0:
                                str_value = str(sum_value)
                                if is_distinct:
                                    if str_value not in values:
                                        values.append(str_value)
                                else:
                                    values.append(str_value)

                # Set the aggregation value
                # - For distinct fields: only join non-empty values, no empty placeholders
                # - For non-distinct fields: include all values including empty placeholders
                # - When no matches found: return "" for distinct, 0 for non-distinct
                # - When matches found but all values empty: return 0
                non_empty_values = [v for v in values if v]
                if non_empty_values:
                    if is_distinct:
                        # Distinct: only join non-empty unique values
                        record[snake_field_name] = ', '.join(non_empty_values)
                    else:
                        # Non-distinct: include all values (with empty placeholders)
                        record[snake_field_name] = ', '.join(values)
                elif has_any_match:
                    # Matches found but all values are empty -> 0
                    record[snake_field_name] = 0
                elif is_distinct:
                    # No matches found, distinct field -> ""
                    record[snake_field_name] = ""
                else:
                    # No matches found, non-distinct field -> 0
                    record[snake_field_name] = 0

    return records
